version: '3.2'
services:
  surved-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - surved-mongo-db
    volumes:
      - source:.
  surved-mongo-db:
    image: mongo:3.4.2
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
volumes:
  db-data: