type Survey implements IAbstract {
    title: String!
    created: Number!
    active: Boolean!
}

type Question implements IAbstract {
    surveyId: ID!
    question: String!
    type: String!
}

type TextQuestion implements IBaseQuestion {
    type: 'text'
    multiLine: boolean
}

type ChoiceQuestion implements IBaseQuestion {
    type: 'select' | 'radio'
}

type Option implements IAbstract {
    questionId: ID!
    text: String!
    image: String
}

type UserOption implements IAbstract {
    optionId: ID!
    userId: ID!
}

type UserText implements IAbstract {
    userId: ID!
    text: String!
}
